ASDKSample/ASDKSample.xcodeproj/xcshareddata/xcschemes/ASDKSample.xcscheme, ASDKSample/Podfile, ASDKSample/Podfile.lock, TinkoffASDKCore.podspec, TinkoffASDKCore/TinkoffASDKCore/IPAddress.swift, TinkoffASDKCore/TinkoffASDKCore/IPAddressFactory.swift, TinkoffASDKCore/TinkoffASDKCore/IPAddressValidator.swift, TinkoffASDKCore/TinkoffASDKCore/IPv4Address.swift, TinkoffASDKCore/TinkoffASDKCore/IPv6Address.swift, TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift, TinkoffASDKCore/TinkoffASDKCore/Utils.swift, TinkoffASDKCore/TinkoffASDKCoreTests/IPAddressTests/IPAddressValidatorTests.swift, TinkoffASDKCore/TinkoffASDKCoreTests/IPAddressTests/IPv4AddressTests.swift, TinkoffASDKCore/TinkoffASDKCoreTests/IPAddressTests/IPv6AddressTests.swift
- add IPv4Address and IPv6Address and tests for them
- add IPAddressValidator and tests for it
- add IPAddressFactory
- rename IPAddress enum to IPAddressProvider and use IPAddress to provide full address for IPv6Address
=> fix IPv6 issue

TinkoffASDKCore/TinkoffASDKCore/API/APICommonParametersProvider.swift, TinkoffASDKCore/TinkoffASDKCore/API/APIConstants.swift, TinkoffASDKCore/TinkoffASDKCore/API/APIHostProvider.swift, TinkoffASDKCore/TinkoffASDKCore/API/APIParametersProvider.swift, TinkoffASDKCore/TinkoffASDKCore/API/APIURLBuilder.swift, TinkoffASDKCore/TinkoffASDKCore/API/APIVersion.swift, TinkoffASDKCore/TinkoffASDKCore/API/AcquiringSdkEnvironment+APIEnvironmentProvider.swift, TinkoffASDKCore/TinkoffASDKCore/API/Implementations/AcquiringAPI.swift, TinkoffASDKCore/TinkoffASDKCore/API/Implementations/AcquiringAPIResponseDecoder.swift, TinkoffASDKCore/TinkoffASDKCore/API/Implementations/AcquiringTokenBuilder.swift, TinkoffASDKCore/TinkoffASDKCore/API/Interfaces/API.swift, TinkoffASDKCore/TinkoffASDKCore/API/Interfaces/APIEnvironmentProvider.swift, TinkoffASDKCore/TinkoffASDKCore/API/Interfaces/APIRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Interfaces/APIResponseDecoder.swift, TinkoffASDKCore/TinkoffASDKCore/API/Interfaces/APITokenBuilder.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/InitPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/InitRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Responses/APIResponse.swift, TinkoffASDKCore/TinkoffASDKCore/AcquiringModels.swift, TinkoffASDKCore/TinkoffASDKCore/Network/Implementations/DefaultNetworkClient.swift, TinkoffASDKCore/TinkoffASDKCore/Network/Interfaces/HTTPHostProvider.swift, TinkoffASDKCore/TinkoffASDKCore/Network/Interfaces/NetworkClient.swift, TinkoffASDKCore/TinkoffASDKCore/Network/URL+HTTPHostProvider.swift
=> MIC 2751 | API Layer

ASDKSample/ASDKSample/BuyProductsViewController.swift, TinkoffASDKCore/TinkoffASDKCore/API/APIConstants.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/AddCardPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/AttachCardPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/ChargePaymentPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/Check3DSVersionPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/FinishAuthorizePayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/GetPaymentStatePayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/RequestData/Check3DSRequestData.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/AddCardRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/AttachCardRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/ChargePaymentRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/Check3DSVersionRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/GetCardListRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/GetPaymentStateRequest.swift, TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift, TinkoffASDKCore/TinkoffASDKCore/CardListDataProvider.swift, TinkoffASDKCore/TinkoffASDKCore/PaymentCardRequests.swift, TinkoffASDKCore/TinkoffASDKCore/PaymentFinishRequest.swift, TinkoffASDKCore/TinkoffASDKCore/PaymentStatusServiceProvider.swift, TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
Check3DSVersionRequest
GetPaymentStateRequest
ChargePaymentRequest
GetCardListRequest
AddCardRequest
AttachCardRequest
=> MIC 2823(part2) | API Layer integration 

TinkoffASDKCore/TinkoffASDKCore/API/APIConstants.swift, TinkoffASDKCore/TinkoffASDKCore/API/Implementations/AcquiringAPI.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/GetPaymentStatePayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/GetQrPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/GetStaticQrPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/RemoveCardPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/Payloads/SubmitRandomAmountPayload.swift, TinkoffASDKCore/TinkoffASDKCore/API/RequestData/SubmitRandomAmountData.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/GetQrRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/GetStaticQrRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/RemoveCardRequest.swift, TinkoffASDKCore/TinkoffASDKCore/API/Requests/SubmitRandomAmountRequest.swift, TinkoffASDKCore/TinkoffASDKCore/AcquiringModels.swift, TinkoffASDKCore/TinkoffASDKCore/AcquiringSdk.swift, TinkoffASDKCore/TinkoffASDKCore/CardListDataProvider.swift, TinkoffASDKCore/TinkoffASDKCore/PaymentCardRequests.swift, TinkoffASDKCore/TinkoffASDKCore/PaymentQRCodeRequest.swift, TinkoffASDKUI/TinkoffASDKUI/AcquiringUISDK.swift
SubmitRandomAmountRequest
RemoveCardRequest
GetQrRequest
GetStaticQrRequest
=> MIC 2823(part3) | API Layer integration

CHANGELOG.md, TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/SBPNoAvailableBanks/SBPNoAvailableBanksViewController.swift, TinkoffASDKUI/TinkoffASDKUI/SBP/Modules/Services/URLOpener.swift, TinkoffASDKUI/TinkoffASDKUI/SBP/SBPAssembly.swift
- open information url on no available banks screen
=> СБП — выбор банка | Открытие веб-сайта с информацией

TinkoffASDKUI/TinkoffASDKUI/Payments/ChargePaymentProcess.swift
- fixed incorrect cancellation condition in handleChargeResult method for ChargePaymentProcess
=> charge payment issue fix

TinkoffASDKCore/TinkoffASDKCore/NetworkTransport.swift
About padding: https://www.pixelstech.net/article/1457585550-How-does-Base64-work
=> remove base64 padding while encoding creq

TinkoffASDKUI/TinkoffASDKUI/AddNewCardViewController.swift, TinkoffASDKUI/TinkoffASDKUI/CardsViewController.swift, TinkoffASDKUI/TinkoffASDKUI/InputCardRequisitesTableViewCell.swift, TinkoffASDKUI/TinkoffASDKUI/InputCardRequisitesTableViewCell.xib, TinkoffASDKUI/TinkoffASDKUI/PaymentCardCollectionViewCell.xib, TinkoffASDKUI/TinkoffASDKUI/PaymentCardInputRequisitesCollectionViewCell.xib, TinkoffASDKUI/TinkoffASDKUI/ScrollableTableViewCell.xib
fix class modules in xibs
fix typo in InputCardRequisitesTableViewCell name
=> [MIC-5055]

TinkoffASDKUI/TinkoffASDKUI/AddNewCardViewController.swift, TinkoffASDKUI/TinkoffASDKUI/CardsViewController.swift, TinkoffASDKUI/TinkoffASDKUI/InputCardRequisitesTableViewCell.swift, TinkoffASDKUI/TinkoffASDKUI/InputCardRequisitesTableViewCell.xib, TinkoffASDKUI/TinkoffASDKUI/PaymentCardCollectionViewCell.xib, TinkoffASDKUI/TinkoffASDKUI/PaymentCardInputRequisitesCollectionViewCell.xib, TinkoffASDKUI/TinkoffASDKUI/ScrollableTableViewCell.xib
fix class modules in xibs
fix typo in InputCardRequisitesTableViewCell name
=> [MIC-5055] (v3) Fix class modules in xibs

TinkoffASDKCore/TinkoffASDKCore/API/Implementations/AcquiringAPIResponseDecoder.swift, TinkoffASDKCore/TinkoffASDKCore/API/Responses/APIFailureError.swift, TinkoffASDKCore/TinkoffASDKCore/API/Responses/APIResponse.swift, TinkoffASDKCore/TinkoffASDKCoreTests/API/Implementations/AcquiringAPIIntegrationTests.swift
Добавил параметры в `APIFailureError`.
=> [MIC-6125] Add params to `APIFailureError`

CHANGELOG.md, TinkoffASDKCore/TinkoffASDKCore/PaymentInitRequest.swift
Добавил параметры `successURL` и `failURL` для возврата в приложение.
=> [MIC-5967] Add params to `PaymentInitData`

CHANGELOG.md, TinkoffASDKCore/TinkoffASDKCore/API/PaymentInitDataParamsEnricher/PaymentInitDataParamsEnricher.swift, TinkoffASDKCore/TinkoffASDKCore/Utils.swift
В запрос `Init` добавлены параметры:
-  `software_version `
-  `device_model `
=> [MIC-6123] Add parameters to `Init` request

TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
=> modalViewController.popupStyle fix

CHANGELOG.md, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/DeviceInfoParams.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/PaymentCardCheckType.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/RequestData/AddCardData.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/RequestData/AttachCardData.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Requests/Implementations/AttachCardRequest.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Responses/Payloads/AddCardPayload.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Responses/Payloads/Check3DSVersionPayload.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/Providers/CardListDataProvider.swift, TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
* Исправил флоу привязки карт через 3DS V2
* Заменил вызовы `deprecated` методов в CardListDataProvider на новые из `v3/root`
=> [MIC-6888] Fix 3DS V2 handling for cards attaching

ASDKSample/ASDKSample/BuyProductsViewController.swift, CHANGELOG.md, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/MainFormStub.swift, TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
Добавлена точка входа с выбором заглушки состояний
=> [MIC-7703] MainForm - Add entry point in ASDKSample

CHANGELOG.md, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Assembly/IMainFormAssembly.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Assembly/MainFormAssembly.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Presenter/IMainFormPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Presenter/MainFormPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Router/IMainFormRouter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Router/MainFormRouter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Views/IMainFormViewController.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Views/MainFormHeaderView.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Views/MainFormViewController.swift, TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift
Реализовал скелет модуля MainForm
=> [MIC-7702] MainForm - MVP module foundation

ASDKSample/ASDKSample/BuyProductsViewController.swift, CHANGELOG.md, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Assembly/IMainFormAssembly.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Assembly/MainFormAssembly.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Models/MainFormStub.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Models/MainFormUIConfiguration.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Presenter/MainFormPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Router/IMainFormRouter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Router/MainFormRouter.swift, TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift, TinkoffASDKUI/TinkoffASDKUI/UIComponents/Views/SavedCard/View/SavedCardView.swift
- протянул платежные данные до роутера 
- поправил высоту SavedCardView
=> MIC-7828: MainForm - Provide payment data to CardPaymentForm

ASDKSample/ASDKSample/BuyProductsViewController.swift, CHANGELOG.md, TinkoffASDKUI/TinkoffASDKUI/Common/Models/PaymentResult.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/CardPayment/Presenter/CardPaymentPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/CommonSheet/ViewController/CommonSheetViewController.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/CommonSheet/Views/CommonSheetView.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Assembly/IMainFormAssembly.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Assembly/MainFormAssembly.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Presenter/IMainFormPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Presenter/MainFormPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Router/IMainFormRouter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Router/MainFormRouter.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Views/ViewController/IMainFormViewController.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/MainForm/Views/ViewController/MainFormViewController.swift, TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentController.swift, TinkoffASDKUI/TinkoffASDKUI/PaymentModule/Payments/PaymentFlow.swift, TinkoffASDKUI/TinkoffASDKUI/SDK/AcquiringUISDK.swift, TinkoffASDKUI/TinkoffASDKUI/YandexPay/Implementations/YandexPayPaymentFlow/YandexPayPaymentFlow.swift, TinkoffASDKUI/TinkoffASDKUI/YandexPay/Implementations/YandexPayPaymentSheet/YandexPayPaymentSheetPresenter.swift, TinkoffASDKUI/TinkoffASDKUI/YandexPay/Interfaces/IYandexPayPaymentSheetOutput.swift
- Добавил логику оплаты по сохраненной карте в MainForm
- Добавил логику закрытия и возврата статуса в родительское приложение из MainForm и CardPayment
- Исправил ошибку с отправкой email в CardPayment
- Переименовал метод во флоу YandexPay
=> MIC-8013: MainForm - Card payment logic

TinkoffASDKUI/TinkoffASDKUI/Common/Models/ASDKErrors.swift, TinkoffASDKUI/TinkoffASDKUI/Modules/CardList/Presenter/CardListPresenter.swift, TinkoffASDKUI/TinkoffASDKUITests/TestCases/CardListPresenterTests.swift
=> MIC-8369 // Не отображается кнопка "Добавить карту" для нового пользователя

ASDKSample/ASDKSample/BuyProductsViewController.swift
**Фикс бага - кнопка ЯП не прожималась**
=> EACQAPW-4444 // Поправить делегат для интеграции YandexPay

.github/workflows/check-changelog.yml
=> Cleaning tinkoff-bot CHANGELOG.md comment if exists

ASDKSample/ASDKSample/BuyProductsViewController.swift, ASDKSample/Podfile.lock, CHANGELOG.md, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/FfdVersion.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/Receipt.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/ReceiptFdv1_05.swift, TinkoffASDKCore/TinkoffASDKCore/Domain/AcquiringAPI/Models/ReceiptFdv1_2.swift, TinkoffASDKUI/TinkoffASDKUITests/TestCases/SBPServices/SBPPaymentService/SBPPaymentServiceTests.swift
Разделил модель `Receipt` на две модели:
- `ReceiptFdv1_05`
- `ReceiptFdv1_2`
=> [EACQAPW-5763]: Реализовал передачу параметров для фискализации 
